name       : carla
version    : 2.0.0
release    : 2
source     :
    - git|https://github.com/falkTX/Carla.git : v2.0.0
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Fully-featured audio plugin host
description: |
    Carla is a fully-featured audio plugin host, with support for many audio drivers and plugin formats.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fftw3)
    - pkgconfig(fluidsynth)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libavcodec)
    - pkgconfig(liblo)
    - pkgconfig(libpulse)
    - pkgconfig(lrdf)
    - pkgconfig(mxml)
    - pkgconfig(sndfile)
    - pkgconfig(Qt5Core)
    - pkgconfig(x11)
    - fltk-devel
    - python-qtpy
rundeps    :
    - jack-audio-connection-kit
    - lrdf
    - python-pyliblo
    - python-qtpy
build      : |
    %patch -p1 < $pkgfiles/fix-compile-with-qt5.13-and-gcc9.patch
    %make features
    %make
install    : |
    %make_install PREFIX=/usr