name       : carla
version    : 2.5.4
release    : 20
source     :
    - git|https://github.com/falkTX/Carla.git : v2.5.4
homepage   : https://kx.studio/Applications:Carla
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Fully-featured audio plugin host
description: |
    Carla is a fully-featured audio plugin host, with support for many audio drivers and plugin formats.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(alsa)
    - pkgconfig(fftw3)
    - pkgconfig(fluidsynth)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libavcodec)
    - pkgconfig(liblo)
    - pkgconfig(libprojectM)
    - pkgconfig(libpulse)
    - pkgconfig(lrdf)
    - pkgconfig(mxml)
    - pkgconfig(sndfile)
    - fltk-devel
    - python3-qt5
rundeps    :
    - lrdf
    - python-pyliblo
    - python3-qt5
setup      : |
    # Ugly way for fix missing "include array" via sed, because patching fails.
    sed -i '27 i\#include <array>' source/modules/juce_gui_basics/native/x11/juce_linux_XWindowSystem.cpp
build      : |
    %make features
    %make
install    : |
    %make_install PREFIX=/usr

    # Fix appstream processing
    mv $installdir/usr/share/applications/{carla.desktop,studio.kx.carla.desktop}
